package org.entredeux.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Papier & encre: paper, blue-black ink and one accent, the blue of a
// fountain pen. At night the paper turns to a warm black and the accent to
// candlelight. Neutrals lean warm, toward the launcher icon's umber.
val PapierColors = lightColorScheme(
    primary = Color(0xFF2B4C9B),
    onPrimary = Color(0xFFF7F4EE),
    primaryContainer = Color(0xFFD9E0F2),
    onPrimaryContainer = Color(0xFF14244A),
    inversePrimary = Color(0xFFAFC2F0),
    secondary = Color(0xFF6B5A46),
    onSecondary = Color(0xFFF7F4EE),
    secondaryContainer = Color(0xFFE6DCCD),
    onSecondaryContainer = Color(0xFF2B2116),
    tertiary = Color(0xFF4E6B4A),
    onTertiary = Color(0xFFF7F4EE),
    tertiaryContainer = Color(0xFFD6E4D0),
    onTertiaryContainer = Color(0xFF15230F),
    background = Color(0xFFF2EEE6),
    onBackground = Color(0xFF1D2433),
    surface = Color(0xFFF2EEE6),
    onSurface = Color(0xFF1D2433),
    surfaceVariant = Color(0xFFE6E0D5),
    onSurfaceVariant = Color(0xFF5B6273),
    surfaceTint = Color(0xFF2B4C9B),
    inverseSurface = Color(0xFF2A2F3A),
    inverseOnSurface = Color(0xFFF2EEE6),
    error = Color(0xFF9A3B2E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF3D9D3),
    onErrorContainer = Color(0xFF3D0F08),
    outline = Color(0xFFB3AA9B),
    outlineVariant = Color(0xFFD9D1C4),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF7F4EE),
    surfaceDim = Color(0xFFE3DDD2),
    surfaceContainerLowest = Color(0xFFFBF9F5),
    surfaceContainerLow = Color(0xFFF6F2EB),
    surfaceContainer = Color(0xFFEEE9E0),
    surfaceContainerHigh = Color(0xFFE9E3D8),
    surfaceContainerHighest = Color(0xFFE3DCD0),
)

// L'heure bleue: the pause between six and ten in the evening, when the
// system is in light mode. Dusk blue with pale, cool dots.
val HeureBleueColors = darkColorScheme(
    primary = Color(0xFFCFDAF6),
    onPrimary = Color(0xFF1E2740),
    primaryContainer = Color(0xFF34405F),
    onPrimaryContainer = Color(0xFFE3E9F9),
    inversePrimary = Color(0xFF2B4C9B),
    secondary = Color(0xFFC9B08E),
    onSecondary = Color(0xFF2E2415),
    secondaryContainer = Color(0xFF3A4260),
    onSecondaryContainer = Color(0xFFE3E9F9),
    background = Color(0xFF1E2740),
    onBackground = Color(0xFFEEF0F6),
    surface = Color(0xFF1E2740),
    onSurface = Color(0xFFEEF0F6),
    surfaceVariant = Color(0xFF2A3452),
    onSurfaceVariant = Color(0xFFAEB7CC),
    surfaceTint = Color(0xFFCFDAF6),
    inverseSurface = Color(0xFFEEF0F6),
    inverseOnSurface = Color(0xFF1E2740),
    error = Color(0xFFE39A8A),
    onError = Color(0xFF3D0F08),
    outline = Color(0xFF6B7797),
    outlineVariant = Color(0xFF34405F),
    scrim = Color(0xFF000000),
    surfaceContainerLowest = Color(0xFF171F34),
    surfaceContainerLow = Color(0xFF1B2339),
    surfaceContainer = Color(0xFF222B45),
    surfaceContainerHigh = Color(0xFF29324D),
    surfaceContainerHighest = Color(0xFF303A56),
)

val NuitColors = darkColorScheme(
    primary = Color(0xFFE8C68A),
    onPrimary = Color(0xFF2B200F),
    primaryContainer = Color(0xFF4A3C22),
    onPrimaryContainer = Color(0xFFF6E2BD),
    inversePrimary = Color(0xFF7A5F2E),
    secondary = Color(0xFFC9B08E),
    onSecondary = Color(0xFF2E2415),
    secondaryContainer = Color(0xFF463A2A),
    onSecondaryContainer = Color(0xFFEADCC6),
    tertiary = Color(0xFFA6C39E),
    onTertiary = Color(0xFF16261A),
    tertiaryContainer = Color(0xFF2F4430),
    onTertiaryContainer = Color(0xFFD2E6CB),
    background = Color(0xFF15130F),
    onBackground = Color(0xFFEDE5D6),
    surface = Color(0xFF15130F),
    onSurface = Color(0xFFEDE5D6),
    surfaceVariant = Color(0xFF2C2822),
    onSurfaceVariant = Color(0xFFA69E90),
    surfaceTint = Color(0xFFE8C68A),
    inverseSurface = Color(0xFFEDE5D6),
    inverseOnSurface = Color(0xFF2A2620),
    error = Color(0xFFE39A8A),
    onError = Color(0xFF3D0F08),
    errorContainer = Color(0xFF6A2A20),
    onErrorContainer = Color(0xFFF7D7CF),
    outline = Color(0xFF6A6256),
    outlineVariant = Color(0xFF3A352D),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3A352D),
    surfaceDim = Color(0xFF15130F),
    surfaceContainerLowest = Color(0xFF100E0B),
    surfaceContainerLow = Color(0xFF1B1814),
    surfaceContainer = Color(0xFF201D18),
    surfaceContainerHigh = Color(0xFF2A2620),
    surfaceContainerHighest = Color(0xFF353029),
)
